framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    http_cache: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
when@dev:
    framework:
        http_cache: false
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
