nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: B2B sales of high-end mobiles
            version: 1.0.0
        servers:
            - url: "http://localhost:8000/"
              description: Development server
        components:
            securitySchemes:
                Bearer:
                  type: http
                  scheme: bearer
                  bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
