nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: B2B sales of high-end mobiles
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
